### ISSUE TITLE
Header Scroll Up Hidden

### ISSUE THREAD

**Issue by PeterwMcClelland** [PeterwMcClelland/Pin#5]
> [!IMPORTANT]
> Target Completion: ASAP

## Context
Header in in file src/components/Header.js. CSS src/components/Coffee/Coffee.css.

## Description 
Scroll header that disappears and re appears when scrolling. 

## Acceptance Criteria
- [x] Have the header disappear when scrolling down at speed of .3s.
- [x] Have the header re appear when scrolling up at speed of .6s.

## Definition of Done
- [x] Code was tested.
- [x] Code was reviewed by Associate.
- [x] Associate left a comment.

**Comment by Sky-De** [comment]
Hi @PeterwMcClelland , i would like to work on this issue, assign that to me
Thank you

**Comment by PeterwMcClelland** [comment]
I actually just finish this issue, thank you though. @Sky-De
